force-app/main/default/objects/Diary__c/Diary__c.object-meta.xml
<CustomObject>
    <label>日誌</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>日誌名</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>日誌</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diary__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>日付</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Diary_test_handler.cls
public with sharing class Diary_test_handler {
    public void Diary_test_handler(List<Diary__c> objList) {
        // before update の処理
        List<Event> eventsToUpdate = new List<Event>();
        for (Diary__c element : objList) {
            List<Event> events = [SELECT Id, ActivityDate, Field1__c FROM Event WHERE ActivityDate = :element.date__c];
            for (Event a : events) {
                a.Field1__c = element.Id;
                eventsToUpdate.add(a);
            }
        }
        update eventsToUpdate;
    }
}